### ISSUE TITLE
Segfault when incompatible program options selected

### ISSUE THREAD

**Issue by smwesten-usgs** [smwesten-usgs/swb2#24]
The following segfault is triggered when the 'ROOTING_DEPTH_METHOD' is set to 'DYNAMIC' but the 'CROP_COEFFICIENT_METHOD' is set to 'NONE'. The reason for the segfault is that the FAO-56 crop coefficients must have been read in and processed in order for the code in 'rooting_depth__FAO56' to function correctly.

==> need to add guard code to ensure that this incompatible set of options bombs with an actual informative error message.

```
Transforming gridded data in file: "climate_ncfile/tmax_EOBS_2014.nc"
 FROM: '+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs'
 TO:   '+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=1500000 +y_0=0 +ellps=intl +towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68 +units=m +no_defs'
At line 46 of file /mnt/f/projects/swb_development/git/swb2/src/rooting_depth__FAO56.F90
Fortran runtime error: Index '45' of dimension 1 of array 'kcb_method' above upper bound of 0

Error termination. Backtrace:
#0  0x7fb2ad311d1d in ???
#1  0x7fb2ad312825 in ???
#2  0x7fb2ad312bca in ???
#3  0x558d9a47c083 in __rooting_depth__fao56_MOD_update_rooting_depth
        at /mnt/f/projects/swb_development/git/swb2/src/rooting_depth__FAO56.F90:46
#4  0x558d9a401988 in __model_domain_MOD_model_update_rooting_depth_fao56
        at /mnt/f/projects/swb_development/git/swb2/src/model_domain.F90:3268
#5  0x558d9a4b3115 in __daily_calculation_MOD_perform_daily_calculation
        at /mnt/f/projects/swb_development/git/swb2/src/daily_calculation.F90:42
#6  0x558d9a452afa in __model_iterate_MOD_iterate_over_simulation_days
        at /mnt/f/projects/swb_development/git/swb2/src/model_iterate.F90:41
#7  0x558d9a3d94f4 in MAIN__
        at /mnt/f/projects/swb_development/git/swb2/src/main.F90:280
#8  0x558d9a3d98d0 in main
        at /mnt/f/projects/swb_development/git/swb2/src/main.F90:12
```

**Comment by smwesten-usgs** [comment]
Changed algorithm to one that avoids leap year edge case.
